const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const state = {camera:false,monitoring:false,pose:null,face:null,lastVideoTime:-1,events:[],alerts:[],fast:{face:null,arms:null,speech:null},poseFrames:[],countdown:null,backend:false,lastSnapshot:null};
const pages={dashboard:'Command Center',monitor:'Live Monitoring',fast:'FAST Screening',health:'Health Data',alerts:'Alert Center'};

function navigate(target){$$('.page').forEach(p=>p.classList.toggle('active',p.id===target));$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.target===target));$('#page-title').textContent=pages[target];window.scrollTo({top:0,behavior:'smooth'});}
$$('[data-target]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.target)));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2700)}
function now(){return new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});if(!response.ok)throw new Error((await response.json()).error||`Request failed: ${response.status}`);return response.json()}
function displayTime(value){return new Date(value).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function addEvent(title,detail,type='info'){state.events.unshift({title,detail,time:now(),event_type:type});renderEvents()}
async function addAlert(title,detail,urgency='high'){try{renderSnapshot(await api('/api/alerts',{method:'POST',body:JSON.stringify({title,detail,urgency})}))}catch(e){toast(e.message)}}
function renderEvents(){const el=$('#event-list');el.innerHTML=state.events.length?state.events.slice(0,4).map(e=>`<div class="event"><i class="event-dot" style="background:${e.event_type==='danger'?'var(--red)':e.event_type==='warning'?'var(--amber)':'var(--blue)'}"></i><div><strong>${e.title}</strong><small>${e.detail}</small></div><small>${e.created_at?displayTime(e.created_at):e.time}</small></div>`).join(''):'<div class="empty-state">No events recorded in this session.</div>'}
function renderAlerts(){const el=$('#alert-list');el.innerHTML=state.alerts.length?state.alerts.map(a=>`<div class="alert-item"><span class="alert-symbol">!</span><div><strong>${a.title}</strong><small>${a.detail} · ${a.created_at?displayTime(a.created_at):a.time}</small></div><span class="pill ${a.status==='Resolved'?'neutral':''}">${a.status}</span><div class="alert-actions">${a.status==='Open'?`<button class="secondary-button" data-ack="${a.id}">Acknowledge</button>`:a.status==='Acknowledged'?`<button class="secondary-button" data-resolve="${a.id}">Resolve</button>`:''}</div></div>`).join(''):'<div class="empty-state">No caregiver alerts have been generated.</div>';$$('[data-ack]').forEach(b=>b.onclick=()=>updateAlert(b.dataset.ack,'Acknowledged'));$$('[data-resolve]').forEach(b=>b.onclick=()=>updateAlert(b.dataset.resolve,'Resolved'))}
async function updateAlert(id,status){try{renderSnapshot(await api(`/api/alerts/${id}`,{method:'POST',body:JSON.stringify({status})}));toast(`Alert ${status.toLowerCase()}`)}catch(e){toast(e.message)}}
function setStatus(level,title,subtitle,confidence='—'){const b=$('#status-banner');b.className=`status-banner status-${level}`;$('#status-icon').textContent=level==='emergency'?'!':level==='warning'?'△':'✓';$('#status-title').textContent=title;$('#status-subtitle').textContent=subtitle;$('#confidence-value').textContent=confidence}

function renderSnapshot(snapshot){state.backend=true;state.lastSnapshot=snapshot;state.events=snapshot.events||[];state.alerts=snapshot.alerts||[];const p=snapshot.patient;setStatus(p.status,p.status_title,p.status_detail,p.confidence);$('#bp-card').textContent=`${p.systolic}/${p.diastolic}`;$('#glucose-card').textContent=p.glucose;$('#heart-card').textContent=p.heart_rate;$('#spo2-card').textContent=p.spo2;$('#last-update').textContent=`Updated ${displayTime(p.updated_at)} · synthetic stream`;$('#backend-state').textContent='Synthetic backend connected';$('#backend-state').classList.remove('neutral');$('#risk-score').textContent=p.risk_context;renderEvents();renderAlerts();drawVitalTrend(snapshot.readings||[])}
function drawVitalTrend(readings){const c=$('#vital-chart');if(!c)return;const ctx=c.getContext('2d'),dpr=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);if(readings.length<2)return;const values=readings.map(r=>r.heart_rate),min=Math.min(...values)-4,max=Math.max(...values)+4;ctx.strokeStyle='#35d6c1';ctx.lineWidth=2;ctx.beginPath();values.forEach((v,i)=>{const x=i/(values.length-1)*w,y=h-((v-min)/(max-min))*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
async function refresh(){try{renderSnapshot(await api('/api/state'))}catch(e){state.backend=false;$('#backend-state').textContent='Backend disconnected';$('#backend-state').classList.add('neutral')}}

async function loadVision(){try{const vision=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/+esm');const files=await vision.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm');state.pose=await vision.PoseLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task',delegate:'GPU'},runningMode:'VIDEO',numPoses:1});state.face=await vision.FaceLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numFaces:1});$('#model-status').textContent='Vision models ready';$('#model-detail').textContent='Pose and face landmarks run locally in this browser.'}catch(e){console.warn(e);$('#model-status').textContent='Offline demo mode';$('#model-detail').textContent='Vision models could not load. Synthetic scenarios remain functional.'}}
loadVision();

async function toggleCamera(){if(!state.camera){try{const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},facingMode:'user'},audio:false});$('#camera').srcObject=stream;state.camera=true;$('#camera-placeholder').style.display='none';$('#camera-toggle').textContent='Stop camera';$('#camera-state').textContent='Camera on';$('#camera-state').classList.remove('neutral');$('#run-monitoring').disabled=false;requestAnimationFrame(analyzeFrame)}catch(e){toast('Camera permission was not granted')}}else{stopCamera()}}
function stopCamera(){state.monitoring=false;state.camera=false;$('#camera').srcObject?.getTracks().forEach(t=>t.stop());$('#camera').srcObject=null;$('#camera-placeholder').style.display='grid';$('#camera-toggle').textContent='Start camera';$('#run-monitoring').textContent='Start monitoring';$('#run-monitoring').disabled=true;$('#camera-state').textContent='Camera off';$('#camera-state').classList.add('neutral');clearCanvas()}
$('#camera-toggle').onclick=toggleCamera;$('#start-camera-action').onclick=()=>{navigate('monitor');setTimeout(toggleCamera,250)};
$('#run-monitoring').onclick=()=>{state.monitoring=!state.monitoring;$('#run-monitoring').textContent=state.monitoring?'Stop monitoring':'Start monitoring';addEvent(state.monitoring?'Monitoring started':'Monitoring stopped','Camera analysis changed','info')};

const connections=[[11,12],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,24],[23,25],[25,27],[24,26],[26,28]];
function clearCanvas(){const c=$('#overlay');c.getContext('2d').clearRect(0,0,c.width,c.height)}
function drawPose(lm){const c=$('#overlay'),v=$('#camera');c.width=v.videoWidth;c.height=v.videoHeight;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.strokeStyle='#35d6c1';x.lineWidth=3;x.fillStyle='#f5f8fa';connections.forEach(([a,b])=>{if(lm[a].visibility>.45&&lm[b].visibility>.45){x.beginPath();x.moveTo(lm[a].x*c.width,lm[a].y*c.height);x.lineTo(lm[b].x*c.width,lm[b].y*c.height);x.stroke()}});lm.forEach(p=>{if(p.visibility>.55){x.beginPath();x.arc(p.x*c.width,p.y*c.height,3,0,Math.PI*2);x.fill()}})}
function poseFeatures(lm,t){const shoulders=mid(lm[11],lm[12]),hips=mid(lm[23],lm[24]);const trunkDx=hips.x-shoulders.x,trunkDy=hips.y-shoulders.y;const angle=Math.abs(Math.atan2(trunkDy,trunkDx)*180/Math.PI);const visibility=[11,12,23,24,27,28].reduce((s,i)=>s+(lm[i].visibility||0),0)/6;const prev=state.poseFrames.at(-1);const velocity=prev?(hips.y-prev.hipY)/Math.max((t-prev.t)/1000,.016):0;const frame={t,hipY:hips.y,velocity,angle,visibility};state.poseFrames.push(frame);state.poseFrames=state.poseFrames.filter(f=>t-f.t<5000);return frame}
function mid(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
function evaluateFall(f){const recent=state.poseFrames.filter(x=>f.t-x.t<1300);const maxDown=Math.max(0,...recent.map(x=>x.velocity));const horizontal=f.angle<38||f.angle>142;const nearFloor=f.hipY>.67;const lowVisibility=f.visibility<.5;$('#metric-visibility').textContent=`${Math.round(f.visibility*100)}%`;$('#metric-angle').textContent=`${Math.round(f.angle)}°`;$('#metric-velocity').textContent=f.velocity.toFixed(2);$('#metric-position').textContent=horizontal?'Horizontal':'Upright';if(lowVisibility)return;if(maxDown>.38&&horizontal&&nearFloor){triggerFall('Live pose sequence matched the prototype fall rule.',Math.min(.96,.6+maxDown/2))}else if(state.monitoring&&maxDown>.2){setStatus('warning','Instability detected','Rapid body movement detected; collecting more evidence.',`${Math.round(Math.min(.85,maxDown)*100)}%`)}}
async function analyzeFrame(){if(!state.camera)return;const v=$('#camera');if(v.readyState>=2&&state.pose&&v.currentTime!==state.lastVideoTime){state.lastVideoTime=v.currentTime;const t=performance.now();const result=state.pose.detectForVideo(v,t);if(result.landmarks?.[0]){drawPose(result.landmarks[0]);if(state.monitoring)evaluateFall(poseFeatures(result.landmarks[0],t))}}requestAnimationFrame(analyzeFrame)}

function triggerFall(detail,confidence=.89){if(!$('#response-modal').classList.contains('hidden'))return;setStatus('emergency','Possible fall detected','Awaiting a response from the monitored person.',`${Math.round(confidence*100)}%`);$('#response-modal').classList.remove('hidden');let n=15;$('#countdown').textContent=n;state.countdown=setInterval(async()=>{n--;$('#countdown').textContent=n;if(n<=0){clearInterval(state.countdown);$('#response-modal').classList.add('hidden');await addAlert('No response after possible fall','Caregiver notification simulated');toast('Caregiver alert generated')}},1000)}
$('#im-okay').onclick=async()=>{clearInterval(state.countdown);$('#response-modal').classList.add('hidden');try{renderSnapshot(await api('/api/respond',{method:'POST',body:JSON.stringify({response:'okay'})}));toast('Response recorded')}catch(e){toast(e.message)}};
$('#need-help').onclick=async()=>{clearInterval(state.countdown);$('#response-modal').classList.add('hidden');try{renderSnapshot(await api('/api/respond',{method:'POST',body:JSON.stringify({response:'help'})}));toast('Caregiver alert generated')}catch(e){toast(e.message)}};
$('#request-help').onclick=()=>{$('#need-help').click();navigate('alerts')};$('#test-alert').onclick=()=>addAlert('Test caregiver alert','This is a synthetic system test','test');

async function runScenario(name){try{renderSnapshot(await api('/api/scenario',{method:'POST',body:JSON.stringify({scenario:name})}));if(name==='face')state.fast.face='warning';if(name==='arm')state.fast.arms='warning';if(name==='multiple'){state.fast.face='warning';state.fast.arms='warning'}renderFast();if(name==='fall')triggerFall('Synthetic fall scenario selected.',.93)}catch(e){toast(e.message)}}
$$('[data-scenario]').forEach(b=>b.onclick=()=>runScenario(b.dataset.scenario));

async function ensureCamera(){if(!state.camera)await toggleCamera();return state.camera}
async function runFastTest(type){navigate('monitor');if(type!=='speech'&&!await ensureCamera())return;navigate('fast');if(type==='face')runFaceTest();if(type==='arms')runArmTest();if(type==='speech')runSpeechTest()}
$$('.start-test').forEach(b=>b.onclick=()=>runFastTest(b.dataset.test));
function showGuide(text){$('#guided-message').querySelector('p').textContent=text}
async function runFaceTest(){showGuide('Smile naturally and keep your face centered for five seconds.');state.fast.face='testing';renderFast();let vals=[],start=performance.now();const timer=setInterval(()=>{if(!state.face||!state.camera)return;const r=state.face.detectForVideo($('#camera'),performance.now());const l=r.faceLandmarks?.[0];if(l){const eye=Math.hypot(l[33].x-l[263].x,l[33].y-l[263].y)||1;vals.push(Math.abs(l[61].y-l[291].y)/eye)}if(performance.now()-start>5000){clearInterval(timer);if(vals.length<5)state.fast.face='inconclusive';else state.fast.face=(vals.reduce((a,b)=>a+b,0)/vals.length)>.10?'warning':'normal';renderFast();showGuide('Face test complete. Continue with arms and speech.')}},150)}
function runArmTest(){showGuide('Raise both arms and hold them forward for ten seconds. Keep your full upper body visible.');state.fast.arms='testing';renderFast();let diffs=[],start=performance.now();const timer=setInterval(()=>{const frames=state.poseFrames.filter(f=>performance.now()-f.t<500);if(state.pose&&state.camera){const r=state.pose.detectForVideo($('#camera'),performance.now());const l=r.landmarks?.[0];if(l&&l[15].visibility>.55&&l[16].visibility>.55)diffs.push(Math.abs(l[15].y-l[16].y))}if(performance.now()-start>10000){clearInterval(timer);if(diffs.length<8)state.fast.arms='inconclusive';else state.fast.arms=Math.max(...diffs)>.14?'warning':'normal';renderFast();showGuide('Arm test complete. The prototype compares wrist-height difference over time.')}},160)}
function runSpeechTest(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){state.fast.speech='inconclusive';renderFast();showGuide('Speech recognition is unavailable in this browser. Marked inconclusive.');return}showGuide('Please say: “The sky is blue today.”');state.fast.speech='testing';renderFast();const r=new SR();r.lang='en-US';r.interimResults=false;r.onresult=e=>{const text=e.results[0][0].transcript.toLowerCase().replace(/[^a-z ]/g,'');const expected=['sky','blue','today'];const matched=expected.filter(w=>text.includes(w)).length;state.fast.speech=matched>=3?'normal':'warning';renderFast();showGuide(`Captured: “${text}”. Transcription mismatch alone is not a diagnosis.`)};r.onerror=()=>{state.fast.speech='inconclusive';renderFast()};r.start()}
function renderFast(){for(const k of ['face','arms','speech']){const el=$(`#${k}-result`),v=state.fast[k];el.className='test-result';el.textContent=!v?'Not tested':v==='testing'?'Testing…':v==='normal'?'No warning sign detected':v==='warning'?'Possible warning sign':'Inconclusive';if(v==='normal')el.classList.add('success');if(v==='warning')el.classList.add('danger');if(v==='inconclusive'||v==='testing')el.classList.add('warning')}const count=Object.values(state.fast).filter(x=>x==='warning').length;$('#fast-summary').textContent=count>=2?'Multiple warning signs':count===1?'One warning sign':'Awaiting evaluation'}
$('#evaluate-fast').onclick=async()=>{const count=Object.values(state.fast).filter(x=>x==='warning').length;await runScenario(count>=2?'multiple':count===1?'arm':'normal');navigate('dashboard')};

$('#health-form').onsubmit=async e=>{e.preventDefault();const payload={age:+$('#age').value,systolic:+$('#systolic').value,diastolic:+$('#diastolic').value,glucose:+$('#glucose').value,heart_rate:+$('#heart-rate').value,spo2:+$('#spo2').value,hypertension:$('#hypertension').checked,diabetes:$('#diabetes').checked,afib:$('#afib').checked,previous_stroke:$('#previous-stroke').checked,heart_disease:$('#heart-disease').checked,smoking:$('#smoking').checked};try{renderSnapshot(await api('/api/health-context',{method:'POST',body:JSON.stringify(payload)}));toast('Health context saved')}catch(e){toast(e.message)}};
$('#reset-demo').onclick=async()=>{try{renderSnapshot(await api('/api/reset',{method:'POST',body:'{}'}));state.fast={face:null,arms:null,speech:null};renderFast();toast('Synthetic session reset')}catch(e){toast(e.message)}};
$('#privacy-btn').onclick=()=>toast('Video is processed locally; no recording is enabled.');
window.addEventListener('beforeunload',stopCamera);
refresh();setInterval(refresh,2000);
